services:

  app-blue:

    container_name: ${COMPOSE_PROJECT_NAME}-blue
    image: ghcr.io/back-2-95/blue-green-app:build-${BUILD_BLUE:?Build number for Blue is missing}
    restart: unless-stopped
    environment:
      TEST_BUILD: ${BUILD_BLUE}
      TEST_INSTANCE: blue
    networks:
      - default
      - traefik-network

  app-green:

    container_name: ${COMPOSE_PROJECT_NAME}-green
    image: ghcr.io/back-2-95/blue-green-app:build-${BUILD_GREEN:?Build number for Green is missing}
    restart: unless-stopped
    environment:
      TEST_BUILD: ${BUILD_GREEN}
      TEST_INSTANCE: green
    networks:
      - default
      - traefik-network

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
  traefik-network:
    external: true
    name: ${TRAEFIK_NETWORK:-traefik-network}
