name: Deploy

on:
  release:
    types: [ published ]
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'Dockerfile'
      - 'index.php'
  workflow_dispatch:

jobs:

  build:

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    uses: requirecloud/gha-workflows/.github/workflows/docker-image-build.yml@main
    with:
      image: ghcr.io/${{ github.repository }}
      platforms: linux/arm64
    secrets: inherit

  deploy:

    needs: [ build ]

    permissions:
      contents: read
      packages: read

    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:

      - uses: actions/checkout@v5

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          use-cache: 'true'

      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
          config: |
            Host ineen
              HostName ineen
              StrictHostKeyChecking no
              ControlMaster auto
              ControlPath ~/.ssh/control-%C
              ControlPersist yes

      - name: Set context
        run: BUILD=${{ github.run_number }} make debug

      - name: Validate Docker Compose config
        run: BUILD=${{ github.run_number }} make config

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start up container with new image
        run: BUILD=${{ github.run_number }} make deploy

      - name: Check that new service is up and healthy
        run: make test-health

      - name: Switch router
        run: make switch-router

      - name: Clear old images
        run: |
          env $(grep -v '^#' .env.prod | xargs) \
          docker image prune -a --force \
          --filter "label=org.opencontainers.image.source=https://github.com/${{ github.repository }}"
